### ISSUE TITLE
As a user I want a JavaScript stack trace console with source map support

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#1006]
As a user I want a JavaScript stack trace console with source map support so that I can directly jump to a location in n4js code identified by a stack trace of the javascript code.

h2. Acceptance Criteria

- [x] locations of stack traces are navigable to the N4JS code from the IO console
- [x] a new console view exists similar to the Java stack trace view which also navigates to the N4JS code
- [x] the test view error view also detects links to source code and navigates to N4JS code

**Comment by qtran-n4** [comment]
It is already pretty cool what you have done. Further improvements are:

1) In the console log (and test result console), the URL still points to the generated JS file. Would be cool if we would use the information in the source map to replace it with a link to the N4JS file (if found).

```
(SystemJS) Cannot read property 'length' of undefined
	TypeError: Cannot read property 'length' of undefined
	    at execute (/Users/quang.tran/oomph/ECL1/idews/Test/src-gen/A.js:99:24)
	    at <anonymous>
	Error loading Test/src-gen/A

```

2) Right now, in the test result console, when we hover the mouse over the links, a dialog pops up and we can choose to jump to either N4JS or JS file. Would be also cool if we can turn the file path to file links and point directly to N4JS file (if found) and JS file otherwise.

3) Tests for the feature
