### ISSUE TITLE
Fix corner case when requested npm package was installed to a nested node_modules folder but not to the top level node_modules folder

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1070]
In corner cases and in bug scenarios it can happen that an npm package was not installed into the node_modules folder of N4JS-IDE. If this happens, an exception is thrown at the moment, since this marks an inconsistent state.
However, it would be better to log the problem instead of throwing an exception.

**Comment by lbeurerkellner** [comment]
I remember that we talked about this case, but from this description I would think that the scenario that we came up with here, cannot occur:

Assume that you install some package A using the library manager. After the installation, A will be listed as dependency in your `.n4npm/package.json` file and thus must also exist in the corresponding `node_modules` folder. Isn't this the minimal guarantee that npm gives you? Otherwise, I do not see how the node module resolution algorithm would be able to locate `A`.

**Comment by mmews-n4** [comment]
I agree, the description is maybe unrealistic.
