### ISSUE TITLE
As a smith I want to use ResourceSet's LiveScope during rename refactoring

### ISSUE THREAD

**Issue by qtran-n4** [eclipse/n4js#1296]
In https://github.com/eclipse/n4js/issues/1002 we have a functioning version of rename refactoring. However, in that implementation, we used a hack to use ResourceSet of load option PersistedDescription instead of ResourceSet of load option LiveScope (see class `N4JSRefactoringResourceSetProvider`). The problem is: if we use LiveScope, the rename refactoring would trigger almost a full build.

We need to find a way to correctly use ResourceSet of load option LiveScope.

**Comment by szarnekow** [comment]
Rather than using the LIVE_SCOPE, we should assess the `SourceLevelURIAdapter` feature. During rename, only the transitive closure of the resource (`#isAffected`), that contains the declaration, needs to be loaded from source (see also `CanLoadFromSourceHelper`. All other index entries remain valid. Disabling the LIVE_SCOPE may cause friction with renamed elements and the scoping semantics. It's to be assessed, which scenarios are broken due to the usage of PERSISTED_DESCRIPTIONS while renaming an element.
