### ISSUE TITLE
N4IDL to ECMAScript Transpiler emits broken import statements for versioned types

### ISSUE THREAD

**Issue by lbeurerkellner** [eclipse/n4js#1356]
( Hey there, it's been a while :) )

Consider a project with the following two N4IDL files:

A.n4idl
```ts
export public class A#1 {}
export public class A#2 {}
```

Client.n4idl
```ts
import {A} from "A";

@VersionAware
export public class Client {
	a1 : A#1
	a2 : A#1
}
```

The N4IDL to ECMAScript transpiler emits the following code for `Client.n4idl`:

```ts
// Generated by N4JS transpiler; for copyright see original N4JS source file.

import 'n4js-runtime'
import  from './A'

export function Client() {
	this.a1 = undefined;
(...)
```

The import statement for `A` is broken. Correct would be `import {A$1} from './A'` (or more versions, depending on the versions that are actually being referenced). I suspect that the move to ECMAScript import statements was not implemented for versioned types.

Unfortunately this renders executable N4IDL code unusable for now.

**Comment by mor-n4** [comment]
This was more tricky than I thought, because removal of unused imports in the output code (at the end of transpilation) interacted with the transpilation of versioned imports in a confusing way.

In your example, the output code should not have an import at all, because A is only used in type declarations and they are removed during transpilation, hence the import would be unused in the output code.

An example that actually has a versioned import in the output code and should produce the output code you mentioned above (but it also did not work):
```javascript
import {A} from "A";

@VersionAware
export public class Client {
	a1 : A#1
	a2 : A#1

	m() {
		A#1;
	}
}
```

I'll push a preliminary fix in a few minutes.

**Comment by mor-n4** [comment]
@lbeurerkellner please check if this works for you.

**Comment by lbeurerkellner** [comment]
Looks good to me. I could successfully run my test suite based on N4IDL code (which previously failed), so I would consider this fixed.
