### ISSUE TITLE
As a smith I want to reduce memory footprint of LSP builder

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1561]
During #1535 the available memory was increased to build Stdlib, OPR, during tests etc. This is due to the lsp builder, which does not serialize the index and hence keeps resources in the memory.

Acceptance Criteria
- reduce memory footprint
- set memory limit back to 10G in Jenkins file
- set memory limit back to 4G in OPR/Stdlib build files

**Comment by szarnekow** [comment]
The root cause of the high memory footprint appears to be that the entire set of resources in the workspace is kept in memory by the LSP server.

The situation is to be improved by only having open documents in memory with their full AST. Most of the other resources can be fully unloaded, the bigger part of the remaining files can be kept in memory without the AST. The type information is sufficient.

We'll approach this with the following multi-step solution:
- Put all built-in resources into a dedicated resource set. This is made transparent to the project's resource set by using the resource locator abstraction of EMF.
- After a project is built, unload all the AST and keep only the type information in memory.
- If the project is a leaf project in the dependency graph of the currently built projects, unload the entire resource. This is supposed to happen recursively.
- Projects with resources that are currently open, need a special treatment. Here we must switch from the per-project logic to a per-resource approach to figure which resources are safe to be unloaded. This needs to be refined.
