### ISSUE TITLE
Access to Class#n4type should be removed from types defined in n4jsd files

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1626]
... unless these types do declare the annotation `@N4JS` (or state `extends N4Object` if possible at all).

Consider the following example:

**Library.n4jsd**
```ts
export external public class Library {}
```

**Main.n4js**
```ts
import {Library} from "Library";

// FIXME XPECT errors "Couldn't resolve reference to IdentifiableElement 'n4type'." at "n4type"
Library.n4type;

let lib = new Library();
// FIXME XPECT errors "Couldn't resolve reference to IdentifiableElement 'n4type'." at "n4type"
lib.constructor.n4type;

// note that the supertype of Library is not N4Object (as expected)
let n4obj: N4Object;
// XPECT errors "Library is not a subtype of N4Object." at "lib"
n4obj = lib;


// same goes for the constructor
let n4ctor: type{? extends N4Object};
// XPECT errors "constructor{? extends Library} is not a subtype of type{? extends N4Object}." at "lib.constructor"
n4ctor = lib.constructor;
```

**Comment by mor-n4** [comment]
From a quick look, this seems to be caused by outdated code in the scoping:
https://github.com/eclipse/n4js/blob/f8f91a667156907388908fa17fc891e3e54bedd2/plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/members/MemberScopingHelper.xtend#L342-L344

The if-condition is incorrect. Also, `RuleEnvironmentExtensions#collectAllImplicitSuperTypesOfType(RuleEnvironment, Type, RecursionGuard<Type>)` should probably be used there to avoid duplication of logic.
