### ISSUE TITLE
Latest changes to the TestController cause issues in some test runs

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#171]
https://github.com/eclipse/n4js/commit/4f82721b3215942efeaee38f0e023043f138711d#diff-dc73ffc60b8b0f629b12b0310d4e08f8R90

This changes cause issues in some N4JS projects, investigate / revert FQN changes.

**Comment by lbeurerkellner** [comment]
To reduce legacy-FQN use in N4JS I changed the FQN delimiter in a recent PR (#143) to the default delimiter `/` in the generation of the test catalog.

This implied some changes to mangelhaft that required escaping of / in URLs. The choice at the time was to use `$` instead of `/` as FQN delimiter for the IDE Reporter protocol.

Since this has caused some issues with test report generation and console logging, this should be changed so that the FQN delimiter isn't changed but just URL-encoded.

**Comment by lbeurerkellner** [comment]
This issue was fixed in https://github.com/eclipse/n4js/pull/182 and can be closed.
