### ISSUE TITLE
Fix subtype check on identical type refs

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#2048]
At the moment, subtype checks on identical type refs (i.e. actually the same Java reference in the VM to a type) causes a complete check to be executed. Adding a shortcut for this corner case saves 30+ seconds on OPR.

**Comment by mor-n4** [comment]
Just for reference: this short-cut would not have saved much build time in OPR until a few days ago when code changes were introduced that now cause an extensive amount of additional structural subtype checking. In other words, the actual problem lies in structural subtype checking and this short-cut is just a quick fix. See `GH-2047` for further investigation.
