### ISSUE TITLE
Check, clarify, or update comment `WARNING WARNING WARNING` in class NoerrorsXpectMethod

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#215]
Class `NoerrorsXpectMethod` contains comments `*** WARNING *** WARNING *** WARNING ***` and `this class should be deleted`. Check if it is still the case. If not, clean up and delete it.

Otherwise, change comments into more self-explanatory style with more detail, especially since it uses the word `WARNING`: State, why it says WARNING three time. Also state, when this class can be deleted.

https://github.com/eclipse/n4js/blob/master/plugins/org.eclipse.n4js.xpect/src/org/eclipse/n4js/xpect/methods/NoerrorsXpectMethod.java

**Comment by mor-n4** [comment]
Had a quick look at this.

Originally, Xpect did not have a `noerrors` method and the class mentioned in the issue description probably contained a custom implementation for that. Later, when Xpect added such a method to its built-in methods, this was not properly changed / cleaned up in our code. No idea why someone added the comment "this class should be deleted" instead of just deleting it.

So, probably just the outcome of two or more sloppy refactorings.
