### ISSUE TITLE
Can't extract constant.

### ISSUE THREAD

**Issue by BrainMiler** [eclipse/n4js#2468]
To reproduce, select **MyTest.foo+"bar"** and then extract constant.  Error popup says, "Cannot extract this expression - it is not a valid constant."

class MyTest {
	static final String foo= "foo";
	static String cat(final String serial) {
		return MyTest.foo+"bar" +serial;
	}
}

**Comment by mmews-n4** [comment]
Your code snipped is not valid n4js code. It has 14 errors due to wrong syntax: Please mind that in n4js the type annotations are similar to TypeScript and not similar to Java syntax. A correct version would look like:

```ts
class MyTest {
	const foo : string = "foo";
	static cat(serial : string) : string{
		return MyTest.foo+"bar" +serial;
	}
}
```

Secondly note that we do not provide the refactoring "extract constant" at the moment.

Due to these two issues of your bug report I will close it as invalid.
