### ISSUE TITLE
Headless compiler does not support external libraries in N4JSX files

### ISSUE THREAD

**Issue by qtran-n4** [eclipse/n4js#349]
Acceptance criteria:
- Headless compiler supports external libraries in N4JSX files

**Comment by mor-n4** [comment]
A quick look revealed that this is caused by `IN4JSCore` not reporting the project dependencies of the current project when asked for those dependencies by `ProjectImportEnablingScope` (an empty list is returned). The reason for this is a broken dependency injection setup due to the know "multi-language problem", see `IDE-2493`.
