### ISSUE TITLE
As a developer I need proper syntax coloring for async / await

### ISSUE THREAD

**Issue by bsmith-n4** [eclipse/n4js#44]
Syntax coloring is broken in some cases.

(moved from internal bug tracker, original reporter: @torstenkraemer)

**Comment by lbeurerkellner** [comment]
I tried to come up with some example cases which all worked:

```
class A {
	@Final
	public async f() {
		
	}
}

async function b() {
	await new A().f();
}

async function f() {
	await b();
	
	await (async () => await b())();
	(async => b())(1);
}
```

Yield the following highlighting:

![image](https://user-images.githubusercontent.com/17903049/30429266-1dc41110-9957-11e7-8ca7-fed15051d331.png)

The last expression in `f` is not highlighted as a keyword since it isn't one. In this case it is in fact an identifier.
