### ISSUE TITLE
Hiding of shipped libraries breaks when starting the same workspace from a different IDE

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#457]
This error was discovered using a development IDE to start the N4JS-IDE.

**How to reproduce**
* Use Oomph to install two development IDEs
* start N4JS IDE in fresh workspace
* create Hello-World-Project
* run it -> should work
* go to library manager and install 'n4js-node'
* run it -> should fail
* close N4JS IDE
* start N4JS IDE from second development IDE
* run Hello-World -> should work

**Note**
Apparently, hiding is buggy regarding the runners. To verify this, add the following line to `ProjectUtils#getExecModuleAsURI` (inside the `if` statement):
```javascript
println("XX project = " + project.location.toString);
```

**Comment by yoosiba** [comment]
note that those steps rely on bug #456, but it is just a way to reproduce it.
Fixing #456 is separate from fixing this.

**Comment by yoosiba** [comment]
if it is about runners and testers, then it can be issue with persisted run configurations.
I suspect run configurations from one IDE are not used by the other IDE (operating on the same workspace). If that is true, we need to cross check with Eclipse behaviour.

**Comment by yoosiba** [comment]
In eclipse run configurations are persisted via workspace. Tried with two installations of Oxygen and one with Neon, and that seems to work fine.
Different IDE instances should also persist run configuration in the workspace, so that part should work fine.

The issue might be in computed values and/or available information about external libraries.

**Comment by mmews-n4** [comment]
I also can't reproduce it. Close as invalid.
