### ISSUE TITLE
Spec ctor not initializing inherited fields

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#593]
Consider the following code:

``` ts
class A {
    public num: number;
}

class B extends A {
    public str: string;

    public constructor(@Spec spec: ~i~this) {}
}

let b = new B({
    num: 5, // if this property is missing: error
    str: "ff"
})

console.log(b); // prints out B { num: undefined, str: 'ff' }
```

Either the generated code is missing initialization of `A.num` in ctor of `B` or the above should not validate.

copied from https://github.com/NumberFour/n4js/issues/151

**Comment by mor-n4** [comment]
After some experimentation and a few discussions, we decided that the current behavior is correct. A warning wasn't added, because due to no `@SuppressWarnings` it would become annoying.

However, the spec was updated with findings of this investigation and discussions (improved constraints for spec constructor (without semantic changes) and added examples, clarifications).

Closing as fixed.
