### ISSUE TITLE
As a developer I need "find references" to work also in corner cases

### ISSUE THREAD

**Issue by qtran-n4** [eclipse/n4js#73]
The following corner cases have to work as well:

- types referenced in polyfills

- references to functions, especially when imported elsewhere
- references to inferenced types
- types referenced in union/intersection types
- methods indirectly referenced (e.g. x.a.bar() should be found if A.bar() has been searched)
- other cases to be discovered.

Note that this is not a pure UI topic, since "find references" is needed for refactorings etc. as well.

## Acceptance Criteria

- detailed list of all cases (working or not) with xpect tests as examples.

- check different kind of elements (class, interface, function, variable, enum, member) from different locations (same file, same project, different project) with different references (type reference, variable reference, import, import with alias)

- if possible, fixes of minor issues
fix Xpect test method if possible, otherwise create follow-up task with detailed problem description

- create follow-up of more complicated cases with description about effort/hints.

**Comment by jpilgrim** [comment]
Some additional remarks:

How does JDT behave? Look at the following snippet:

```
interface I { 	void foo(); }
interface J extends I { void foo(); }
class A { void foo() {} }
class B extends A { void foo() {} }
class CI implements I { public void foo() {} }
interface K { default void foo() {} }
interface L extends K { default void foo() {} }

//=> interfaces: hierarchy up and down
//=> classes: hierarchy only down (only sub classes)
class C {
	<T extends I & K> void f(CI ci, A a, B b, L l, T t, I i, J j) {
		ci.foo();		// CI.foo, I.foo, ==> "super" interfaces 
		a.foo();		// A.foo, B.foo => sub classes
		b.foo();		// B.foo, not A.foo => not super classes
		l.foo();		// L.foo, K.foo ==> "super" interface 
		t.foo();		// I.foo, K.foo ==> intersection
		i.foo();        // I.foo, J.foo ==> sub interface
		j.foo();        // J.foo, I.foo => super interface
	}
}
```

JDT's findReferences(Method m) with C is owner of m, C is class or interface, finds
* C.m itself
* I.m, I is interface, I<:C || C<:I
* B.m, C is class, C <: B   (i.e. B is a super type of C)

But this is the UI only!

For N4JS findReferences(Method m), we define that internally we find:
* C.m itself
nothing else

In order to "emulate" JDT's behaviour, we might add flags (toggles) in the UI to also consider overridden and overriding methods:
* "consider overridden": B.m, iff C<:B (i.e. we also look in supertypes, which is defined by the extend or implements clauses)
* "consider overriding": C.m, iff D<:B (i.e. we also look in subtypes, which requires to find all subtypes of a classifier)

We do not consider structural typing at the moment! That basically would mean 
* for classes: find all classes that are structurally equal
* for methods: find all methods with override compatible signature
In both cases we need to further investigate how we can refine the search algorithm, since this is too coarse grained.

**Comment by qtran-n4** [comment]
Do not forget to add test cases to cover [https://github.com/eclipse/n4js/issues/132](https://github.com/eclipse/n4js/issues/132)
