### ISSUE TITLE
In manifest files the property 'noValidation' does not work when the source property is "."

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#781]
In the following manifest snippet, the tag `noValidate` does not have any effect. However, if another source folder than `"."` is used in the source property, the `noValidate` does work.

```
ProjectId: react2
ProjectType: library
ProjectVersion: 16.3.2
VendorId: npm
VendorName: "npm"
Output: "."
MainModule: "index"
ModuleLoader: commonjs
Sources {
	source {
        "."
    }
}

ModuleFilters {
    noValidate {
        "cjs/*"
    }
}
```

**Comment by lbeurerkellner** [comment]
Also note, that this type of manifest only works for projects in the external workspace. Since the output folder is specified to be the project root which also happens to be the source folder, an IDE configured with this manifest will find itself in an endless loop of retranspiling the files it puts out.
