### ISSUE TITLE
As a user I need support for dots "." in JavaScript file names

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#818]
Some javascript libraries use dots "." in file names, e.g. vue, or (even worse) js-cookie.
In order to provide n4jsd files (with the same name) we need support for dots.

h2. Acceptance Criteria

Dots are supported in file names. In particular, we have to able to provide n4jsd file for js-cookie (https://github.com/js-cookie/js-cookie/blob/master/src/js.cookie.js) without any hacks.

**Comment by mor-n4** [comment]
A work-around had to be added for `js.cookie`; must be removed by this task (search for string `GH-818` in file `N4JSModuleValidator.xtend`)!

**Comment by mor-n4** [comment]
This is now also required for redux-saga, which introduced dots in the name of its main module during a recent restructuring:
https://github.com/redux-saga/redux-saga/blob/6d7cb99cf489da0b4de72eee44b7333d3c8f2cba/packages/redux-saga/package.json#L5

A solution required to allow defining type information in form of n4jsd files for such a project.

**Comment by mor-n4** [comment]
After looking into this some more, there seem to be at least the following two blockers:
1. Reflection property `fqn` is still using `.` as a delimiter (causing havoc if we would now allow `.` in folder/module names). Changing this requires adjustments in the runtime (maybe N4Injector) and in client code.
2. Links in JSDoc comments following tags such as `@testee`. Note that this does not apply to asciidoc because there a different format is used for the links
   (i.e. PQNs: https://numberfour.github.io/asciispec/spec.html#PQN-def).

I will fix 1. as part of this task and leave 2. for a follow-up task (JSDoc links will work fine as long as no "." is used in folder/module names of N4JS files, including all existing links).
