### ISSUE TITLE
Updating the IDE via 'Help > Check for Updates' breaks shipped code references

### ISSUE THREAD

**Issue by lbeurerkellner** [eclipse/n4js#853]
When updating from an older IDE version (I have tried 201805160446) to the current IDE, references to shipped code such as `Assert` from mangelhaft break. The state manifests itself in that these types are completely missing from the index and cannot be imported nor used.

**Steps to reproduce**:

1. Download an older version of the IDE (e.g. 201805160446)
2. Setup a simple workspace with a project that declares a dependency on `org.eclipse.n4js.mangelhaft.assert`. Furthemore, add a file that imports `Assert` and uses it somehow.
3. Perform an IDE update via 'Help > Check for Updates' and restart the IDE after it finishes updating.
4. After restarting, perform a clean build and have a look at the file that imports `Assert`.

This file will now show validation markers for the import and any usage of `Assert`.

<img src="https://user-images.githubusercontent.com/17903049/40615645-e2ba3004-6287-11e8-84bb-bfea8fdad470.png" width="350px"/>

Note that in the screenshot, we can also see that external libraries (such as react in this example) are not affected by this.

As a workaround, the issues can be resolved by running the maintenance action 'Reset type definitions (creates fresh clone)' of the library manager. Alternatively, the 'Install missing dependencies' (== big button) routine also fixes the issue.

**Proposed Acceptance Criteria**:

Updating the IDE should not require to run the 'Install missing dependencies' routine and therefore not interrupt users of the IDE during their work.

**Comment by mmews-n4** [comment]
I reproduced this bug and apparently, folder names change when updating the IDE. For instance, this is the complete path of the file `http.n4jsd` which is part of n4js-runtime-node:
> file:/private/var/folders/0f/kcrchrgs4_q8hjgvb45x5c4m0000gp/T/AppTranslocation/646E36D9-C88F-4924-BC55-4203ACA279A3/d/n4ide.app/Contents/Eclipse/plugins/org.eclipse.n4js.external.libraries_0.0.1.201805152345/runtime/n4js-runtime-node/src/n4js/http.n4jsd#/1/@topLevelTypes.0


Note the following:
1) the whole path points to some temporary folder that was created by MacOS when double clicking the N4IDE icon
2) the folder `org.eclipse.n4js.external.libraries_0.0.1.201805152345` points to the location of the old (not-updated) version of the IDE. When updating, the trailing version number changes.
3) the above means, that this bug is also reproducable when moving the workspace folder to another location (although then, maybe the node_modules won't work, but the shipped stuff would)
4) This bug gets solved (except for point 3 above) when shipped code won't be shipped anymore (see #887) and the node_modules folder is moved out of a plugin folder but into the workspace folder directly (see #824)
5) Even after #887 and #824 are done, moving the workspace folder will result in workspace errors. This will be solved by making the URIs relative to the workspace folder (see #888).
