### ISSUE TITLE
Integration tests report cyclic dependencies in fabelhaft snapshot code on Jenkins

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#963]
Since (parts of) GH-809 and GH-887 were merged, the fabelhaft integration tests and the tasks example SWTBot test sometimes fail on Jenkins due to cyclic dependencies.

The cycle being reported is `eslint -> js-yaml -> eslint`.

**Comment by lbeurerkellner** [comment]
I am working on this.

**Comment by lbeurerkellner** [comment]
The first part of this issue was related to the invalid detection of cyclic dependencies in external library projects. This was fixed in https://github.com/eclipse/n4js/pull/967. 
The second part however relates to the state of our integration snapshot, which need to be updated in regard to the version constraints of dependencies. Furthermore, an underlying issue regarding the handling of pre-existing target platform locations in the headless compiler has been surfaced.

**Comment by mor-n4** [comment]
@lbeurerkellner has worked on this.
